### ISSUE TITLE
Delay differential equations need a wrapper on the history function

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/diffeqpy#1]
```py
def f(u, h, p, t):
  du1 = 1.1/(1 + 3.16227*(h(p, t-20)[0])**(1.25)) - 10*u[0]/(1 + 40*u[1])
  du2 = 100*u[0]/(1 + 40*u[1]) - 2.43*u[1]
  return[du1,du2]

u0 = [1.05767027/3, 1.030713491/3]
def h(p,t):
  [1.05767027/3, 1.030713491/3]

tspan = (0.0, 100.0)
constant_lags = [20.0]
prob = de.DDEProblem(f,u0,h,tspan,constant_lags=constant_lags)
sol = de.pysolve(prob)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in f
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ChrisRackauckas** [comment]
Works via Julia functions for now.
