### ISSUE TITLE
Cannot run Julia-defined function from example in README

### ISSUE THREAD

**Issue by michaelkyu** [JuliaDiffEq/diffeqpy#35]
I am running Julia 0.6.4 and Python 3.7.0. I tried running the following example from the README to use a Julia-defined function

```
jul_f = de.eval("""
function f(du,u,p,t)
  x, y, z = u
  sigma, rho, beta = p
  du[1] = sigma * (y - x)
  du[2] = x * (rho - z) - y
  du[3] = x * y - beta * z
end""")
u0 = [1.0,0.0,0.0]
tspan = (0., 100.)
p = [10.0,28.0,2.66]
prob = de.ODEProblem(jul_f, u0, tspan, p)
sol = de.solve(prob)
```

But I get the error

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-c07076744217> in <module>
     10 tspan = (0., 100.)
     11 p = [10.0,28.0,2.66]
---> 12 prob = de.ODEProblem(jul_f, u0, tspan, p)
     13 sol = de.solve(prob)

ValueError: Julia exception: ArgumentError("reducing over an empty collection is not allowed")
```

Strangely, the example below that uses a Python-defined function works correctly for me

```
def f(du,u,p,t):
    x, y, z = u
    sigma, rho, beta = p
    du[0] = sigma * (y - x)
    du[1] = x * (rho - z) - y
    du[2] = x * y - beta * z

numba_f = numba.jit(f)
u0 = [1.0,0.0,0.0]
tspan = (0., 100.)
p = [10.0,28.0,2.66]
prob = de.ODEProblem(numba_f, u0, tspan, p)
sol = de.solve(prob)
```

Thanks for the help!

**Comment by ChrisRackauckas** [comment]
The current release might be only v1.0 compatible?

**Comment by michaelkyu** [comment]
I've tried this on Julia 1.0.2, but now I cannot import diffeqpy

```
>>> import diffeqpy
>>> from diffeqpy import de
Traceback (most recent call last):
  File "/home/mikeyu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/julia/core.py", line 808, in __getattr__
    return getattr(self.__julia, name)
AttributeError: 'Julia' object has no attribute 'add_module_functions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mikeyu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/diffeqpy/de.py", line 2, in <module>
    _jul = setup()
  File "/home/mikeyu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/diffeqpy/__init__.py", line 20, in setup
    jul.add_module_functions('DifferentialEquations')
  File "/home/mikeyu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/julia/core.py", line 810, in __getattr__
    return getattr(Main, name)
  File "/home/mikeyu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/julia/core.py", line 107, in __getattr__
    return self.__try_getattr(name)
  File "/home/mikeyu/.pyenv/versions/3.7.0/lib/python3.7/site-packages/julia/core.py", line 132, in __try_getattr
    raise AttributeError(name)
AttributeError: add_module_functions
```

I confirmed that PyCall works for the example on [PyCall's README](https://github.com/JuliaPy/PyCall.jl)

```
julia> using PyCall

julia> @pyimport math

julia> math.sin(math.pi / 4) - sin(pi/4)
0.0

```

I also confirmed that pyjulia works for the example on [pyjulia's README](https://github.com/JuliaPy/pyjulia)

```
>>> from julia import Base
>>> Base.sind(90)
1.0
>>> from julia import Main
>>> Main.xs = [1, 2, 3]
>>> Main.eval("sin.(xs)")
[0.8414709848078965, 0.9092974268256817, 0.1411200080598672]
```

**Comment by ChrisRackauckas** [comment]
@tkf ?

**Comment by tkf** [comment]
As for the 1.0.2 error, it is expected as Julia 1.x (or rather PyJulia 0.2) only works with diffeqpy on git master.  I'm not sure what's going on with Julia 0.6.4 case.  I'll look into it later.

Meanwhile, you can try the following with Julia 1.x and PyJulia 0.2:

```python
from julia import Main

Main.eval("""
using DifferentialEquations
using PyCall

PyCall.PyObject(::typeof(DiffEqBase.solve)) =
    PyCall.pyfunctionret(solve,Any,Vararg{PyCall.PyAny})

const inspect = pyimport("inspect")

function DiffEqBase.numargs(f::PyCall.PyObject)
    haskey(f,:py_func) ? _f = f[:py_func] : _f = f
    if PyCall.pyversion < v"3.0.0"
        return length(first(inspect[:getargspec](_f)))
    else
        return length(first(inspect[:getfullargspec](_f)))
    end
end
""")

from julia import DifferentialEquations as de
```

then try the README example:

```python
# Use Main.eval, not de.eval:
jul_f = Main.eval("""
function f(du,u,p,t)
  x, y, z = u
  sigma, rho, beta = p
  du[1] = sigma * (y - x)
  du[2] = x * (rho - z) - y
  du[3] = x * y - beta * z
end""")

u0 = [1.0,0.0,0.0]
tspan = (0., 100.)
p = [10.0,28.0,2.66]
prob = de.ODEProblem(jul_f, u0, tspan, p)
sol = de.solve(prob)
```

**Comment by michaelkyu** [comment]
This solution works. Thanks!

**Comment by tkf** [comment]
#36 should fix it.

Re:

> ```python
> <ipython-input-2-c07076744217> in <module>
>      10 tspan = (0., 100.)
>      11 p = [10.0,28.0,2.66]
> ---> 12 prob = de.ODEProblem(jul_f, u0, tspan, p)
>      13 sol = de.solve(prob)
> 
> ValueError: Julia exception: ArgumentError("reducing over an empty collection is not allowed")
> ```

This was actually doing something similar to

```julia
jul_f = """
function f(du,u,p,t)
  x, y, z = u
  sigma, rho, beta = p
  du[1] = sigma * (y - x)
  du[2] = x * (rho - z) - y
  du[3] = x * y - beta * z
end"""  # yes, String!
ODEProblem(jul_f, u0, tspan, p)
```

in Julia.  This is because now (due to PyJulia change) `diffeqpy.de.eval` really points to `DifferentialEquations.eval` which is an identity function for a `String`.  Using `Main.eval` instead is the way to go.

**Comment by ChrisRackauckas** [comment]
Yes, now that tests are passing let's do a release and close this.

**Comment by ChrisRackauckas** [comment]
@tkf I added you as an author in the METADATA

**Comment by tkf** [comment]
Thanks! :)

**Comment by ChrisRackauckas** [comment]
Alright, a v1.0-compatible version is on PyPI now.
