### ISSUE TITLE
Error trying to install diffeqpy

### ISSUE THREAD

**Issue by bjodah** [JuliaDiffEq/diffeqpy#4]
This package looks really interesting to me (since most of my work has been using Python so far), thank you for putting in the effort to provide Python bindings (for us who haven't yet gotten on the Julia bandwagon)!

I followed the installation instructions from the README (I'm on a Ubuntu 16.04 machine with Python 3.5 and Julia 0.6.2), and this is how far I got:
```
bjorn@yoga720:~$ python3 -m pip install --user diffeqpy
Collecting diffeqpy
  Downloading https://files.pythonhosted.org/packages/f7/38/07ec0d7703451d81bbf89d2602f306169b18b4a8b69b512d2da0d53a2239/diffeqpy-0.2.tar.gz
Collecting julia (from diffeqpy)
  Downloading https://files.pythonhosted.org/packages/2e/2a/04e16c1b1cde76c669328e09da9e833ee50a9aed4fad2b1fddf137d2d199/julia-0.1.5-py2.py3-none-any.whl (222kB)
    100% |████████████████████████████████| 225kB 7.8MB/s 
Building wheels for collected packages: diffeqpy
  Running setup.py bdist_wheel for diffeqpy ... done
  Stored in directory: /home/bjorn/.cache/pip/wheels/81/32/69/c19322b0bf49ace80a1ddb3d9cd462aead7d2c545ac709e9f7
Successfully built diffeqpy
Installing collected packages: julia, diffeqpy
Successfully installed diffeqpy-0.2 julia-0.1.5
You are using pip version 10.0.0, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
bjorn@yoga720:~$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.2 (2017-12-13 18:08 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> Pkg.add("DiffEqPy")
ERROR: unknown package DiffEqPy
macro expansion at ./pkg/entry.jl:53 [inlined]
(::Base.Pkg.Entry.##1#3{String,Base.Pkg.Types.VersionSet})() at ./task.jl:335
Stacktrace:
 [1] sync_end() at ./task.jl:287
 [2] macro expansion at ./task.jl:303 [inlined]
 [3] add(::String, ::Base.Pkg.Types.VersionSet) at ./pkg/entry.jl:51
 [4] (::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}})() at ./pkg/dir.jl:36
 [5] cd(::Base.Pkg.Dir.##4#7{Array{Any,1},Base.Pkg.Entry.#add,Tuple{String}}, ::String) at ./file.jl:70
 [6] #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{String,N} where N) at ./pkg/dir.jl:36
 [7] add(::String) at ./pkg/pkg.jl:117

julia> 
```

Since I'm new to Julia I'm not sure how to debug this, any ideas?

**Comment by bjodah** [comment]
That helped (I was on 0.6.2 but hadn't run the `Pkg.udpate()` command, and obviously not the checkout either). The example in the README then works under python3.

If I run:
```
$ PYTHONPATH=$(pwd) python3 -m pytest -v
```
it collects the tests (the environment variable is there because I haven't installed the dev repo),
I added a missing import:
```diff
diff --git a/diffeqpy/tests/test_sde.py b/diffeqpy/tests/test_sde.py
index 7b2dbb6..cbaee67 100644
--- a/diffeqpy/tests/test_sde.py
+++ b/diffeqpy/tests/test_sde.py
@@ -1,3 +1,4 @@
+import numba
 import diffeqpy
 de = diffeqpy.setup()
```
But then I get a segfault:
```
00:42 $ PYTHONPATH=$(pwd) python3 -m pytest -v
========================================== test session starts ==========================================
platform linux -- Python 3.5.2, pytest-3.5.0, py-1.5.3, pluggy-0.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/bjorn/rovc/diffeqpy, inifile: setup.cfg
plugins: pep8-1.0.6, flakes-2.0.0
collecting 0 items                                                                                      
Segmentation fault (core dumped)
```
running under gdb suggests that the segault happens in `jl_subtype_env`:
```
$ PYTHONPATH=$(pwd) gdb --ex run --args python3 -m pytest -v
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...(no debugging symbols found)...done.
Starting program: /usr/bin/python3 -m pytest -v
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
========================================== test session starts ==========================================
platform linux -- Python 3.5.2, pytest-3.5.0, py-1.5.3, pluggy-0.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/bjorn/rovc/diffeqpy, inifile: setup.cfg
plugins: pep8-1.0.6, flakes-2.0.0
collecting 0 items                                                                                      [New Thread 0x7fd62cc85700 (LWP 15323)]
[New Thread 0x7fd62179e700 (LWP 15324)]
[New Thread 0x7fd61ef9d700 (LWP 15325)]
[New Thread 0x7fd61e79c700 (LWP 15326)]
[New Thread 0x7fd61bf9b700 (LWP 15327)]
[New Thread 0x7fd61779a700 (LWP 15328)]
[New Thread 0x7fd614f99700 (LWP 15329)]
[New Thread 0x7fd614798700 (LWP 15330)]

Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
jl_subtype_env (x=0x7fd60b3cd510, y=0x7fd6258605b0, env=<optimized out>, envsz=<optimized out>)
    at /buildworker/worker/package_linux64/build/src/subtype.c:1045
1045	/buildworker/worker/package_linux64/build/src/subtype.c: No such file or directory.
(gdb) bt
#0  jl_subtype_env (x=0x7fd60b3cd510, y=0x7fd6258605b0, env=<optimized out>, envsz=<optimized out>)
    at /buildworker/worker/package_linux64/build/src/subtype.c:1045
#1  0x00007fd62a27be4d in isimmutable () at reflection.jl:214
#2  julia_finalizer_2512 () at base.jl:126
#3  0x00007fd60dc8cf8e in Type () at /home/bjorn/.julia/v0.6/PyCall/src/PyCall.jl:71
#4  0x00007fd60dc8cf8e in julia_#20_63262 ()
#5  0x00007fd60dc8c3db in julia_next_63261 () at generator.jl:45
#6  0x00007fd60dc8c43a in jlcall_next_63260 ()
#7  0x00007fd62f314f7a in jl_call_fptr_internal (fptr=<optimized out>, fptr=<optimized out>, 
    nargs=<optimized out>, args=<optimized out>, meth=<optimized out>)
    at /buildworker/worker/package_linux64/build/src/julia_internal.h:339
#8  jl_call_method_internal (nargs=3, args=0x7fffff7ff600, meth=<optimized out>)
    at /buildworker/worker/package_linux64/build/src/julia_internal.h:358
#9  jl_apply_generic (args=0x7fffff7ff600, nargs=3)
    at /buildworker/worker/package_linux64/build/src/gf.c:1926
#10 0x00007fd60dc65cd8 in japi1_append_any_63014 () at essentials.jl:169
#11 0x00007fd62f314f7a in jl_call_fptr_internal (fptr=<optimized out>, fptr=<optimized out>, 
    nargs=<optimized out>, args=<optimized out>, meth=<optimized out>)
    at /buildworker/worker/package_linux64/build/src/julia_internal.h:339
#12 jl_call_method_internal (nargs=3, args=0x7fffff7ff7e8, meth=<optimized out>)
    at /buildworker/worker/package_linux64/build/src/julia_internal.h:358
#13 jl_apply_generic (args=args@entry=0x7fffff7ff7e8, nargs=nargs@entry=3)
    at /buildworker/worker/package_linux64/build/src/gf.c:1926
#14 0x00007fd62f3212b6 in jl_apply (nargs=3, args=0x7fffff7ff7e8)
    at /buildworker/worker/package_linux64/build/src/julia.h:1424
#15 jl_f__apply (F=<optimized out>, args=<optimized out>, nargs=<optimized out>)
    at /buildworker/worker/package_linux64/build/src/builtins.c:359
#16 0x00007fd60dc8aa25 in julia_typetuple_63257 ()
    at /home/bjorn/.julia/v0.6/PyCall/src/conversions.jl:706
#17 0x00007fd60dc8adbc in julia_pysequence_query_63256 ()
    at /home/bjorn/.julia/v0.6/PyCall/src/conversions.jl:715
#18 0x00007fd60dc8b71c in julia_pytype_query_63255 ()
    at /home/bjorn/.julia/v0.6/PyCall/src/conversions.jl:736
#19 0x00007fd60dc8bcba in julia_pytype_query_63254 ()
    at /home/bjorn/.julia/v0.6/PyCall/src/conversions.jl:769
#20 0x00007fd60dc8bde1 in julia_convert_63253 ()
    at /home/bjorn/.julia/v0.6/PyCall/src/conversions.jl:794
#21 0x00007fd60dc8f0eb in julia_next_63275 () at /home/bjorn/.julia/v0.6/PyCall/src/conversions.jl:533
#22 0x00007fd60dc8eb67 in julia_copy_63273 () at associative.jl:114
#23 0x00007fd60dc8ecc3 in jlcall_copy_63272 ()
#24 0x00007fd62f314f7a in jl_call_fptr_internal (fptr=<optimized out>, fptr=<optimized out>, 
    nargs=<optimized out>, args=<optimized out>, meth=<optimized out>)
    at /buildworker/worker/package_linux64/build/src/julia_internal.h:339
#25 jl_call_method_internal (nargs=2, args=0x7fffff800048, meth=<optimized out>)
    at /buildworker/worker/package_linux64/build/src/julia_internal.h:358
#26 jl_apply_generic (args=0x7fffff800048, nargs=2)
    at /buildworker/worker/package_linux64/build/src/gf.c:1926
#27 0x00007fd60dc8e715 in julia_convert_63270 ()
    at /home/bjorn/.julia/v0.6/PyCall/src/conversions.jl:561
#28 0x00007fd60dc8e747 in jlcall_convert_63269 ()
#29 0x00007fd62f314f7a in jl_call_fptr_internal (fptr=<optimized out>, fptr=<optimized out>, 
    nargs=<optimized out>, args=<optimized out>, meth=<optimized out>)
    at /buildworker/worker/package_linux64/build/src/julia_internal.h:339
#30 jl_call_method_internal (nargs=3, args=0x7fffff800270, meth=<optimized out>)
    at /buildworker/worker/package_linux64/build/src/julia_internal.h:358
#31 jl_apply_generic (args=0x7fffff800270, nargs=3)
    at /buildworker/worker/package_linux64/build/src/gf.c:1926
#32 0x00007fd60dc8bebb in julia_convert_63253 ()
    at /home/bjorn/.julia/v0.6/PyCall/src/conversions.jl:798
#33 0x00007fd60dc8f0eb in julia_next_63275 () at /home/bjorn/.julia/v0.6/PyCall/src/conversions.jl:533
#34 0x00007fd60dc8eb67 in julia_copy_63273 () at associative.jl:114
#35 0x00007fd60dc8ecc3 in jlcall_copy_63272 ()
#36 0x00007fd62f314f7a in jl_call_fptr_internal (fptr=<optimized out>, fptr=<optimized out>, 
    nargs=<optimized out>, args=<optimized out>, meth=<optimized out>)
```

**Comment by ChrisRackauckas** [comment]
I would guess that PyCall built against the wrong Python. Try:

```julia
ENV["PYTHON"] = "python3"
Pkg.build("PyCall")
```

**Comment by bjodah** [comment]
Awesome:
```
$ PYTHONPATH=$(pwd) python3 -m pytest -v
========================================== test session starts ==========================================
platform linux -- Python 3.5.2, pytest-3.5.0, py-1.5.3, pluggy-0.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/bjorn/rovc/diffeqpy, inifile: setup.cfg
plugins: pep8-1.0.6, flakes-2.0.0
collected 2 items                                                                                       

diffeqpy/tests/test_ode.py::test_ode_sol PASSED                                                   [ 50%]
diffeqpy/tests/test_ode.py::test_lorenz_sol PASSED                                                [100%]

======================================= 2 passed in 92.84 seconds =======================================
```
